name: Prepare for CI
description: Prepare for CI
inputs:
  node-ver:
    description: The version of Node.js
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-ver }}
        cache: yarn
    - name: Cache node_modules
      uses: actions/cache@v3
      env:
        cache-ver: '1'
      with:
        path: './node_modules'
        key: ${{ runner.os }}-build-v${{ env.cache-ver }}-${{ hashFiles('./yarn.lock') }}
    - name: Install deps
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Generate codes in shared
      run: yarn codegen
      shell: bash
    - name: Build shared package
      run: yarn build:shared
      shell: bash
