# dev用
version: '3.3'
volumes:
  configdb:
services:
  mongo:
    image: mongo:4.4.15
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb-data:/data/db
      - configdb:/data/configdb
