# dev用
version: '3.3'
volumes:
  mariadb:
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: keiba
      TZ: "Asia/Tokyo"
    volumes:
      - mariadb:/var/lib/mysql
