# dev用
version: '3.3'
volumes:
  mongo-primary:
  mongo-secondary:
services:
  mongodb-primary:
    image: mongo:4.4
    restart: always
    command: --replSet rs0 --auth --keyFile /etc/mongod-keyfile
    expose:
      - 27017
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-primary:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./mongo-keyfile:/etc/mongod-keyfile:ro
  mongodb-secondary:
    image: mongo:4.4
    restart: always
    command: --replSet rs0 --auth --keyFile /etc/mongod-keyfile
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-secondary:/data/db
      - ./mongo-keyfile:/etc/mongod-keyfile:ro
  mongodb-arbiter:
    image: mongo:4.4
    restart: always
    command: --replSet rs0 --auth --keyFile /etc/mongod-keyfile
    expose:
      - 27017
    volumes:
      - ./mongo-keyfile:/etc/mongod-keyfile:ro
