name: CI
on:
  push:
    paths-ignore:
      - CODEOWNERS
      - LICENSE
      - README.md
      - renovate.json
      - ".github/workflows/*.yml"
      - "!.github/workflows/ci.yml"
env:
  node-ver: 16
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["@gigantic-minecraft/seichi-keiba-shared", backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Generate codes in shared
        run: yarn codegen
      - name: Build shared package
        run: yarn build:shared
      - name: Run eslint-config-prettier
        run: yarn workspace ${{ matrix.workspace }} lint:conflict
      - name: Run ESLint
        run: yarn workspace ${{ matrix.workspace }} lint
      - name: Run Prettier
        run: yarn workspace ${{ matrix.workspace }} format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Generate codes in shared
        run: yarn codegen
      - name: Build shared package
        run: yarn build:shared
      - name: Build
        run: yarn workspace ${{ matrix.workspace }} build
