name: CI
on:
  push:
    paths-ignore:
      - CODEOWNERS
      - LICENSE
      - README.md
      - renovate.json
      - ".github/workflows/*.yml"
      - "!.github/workflows/ci.yml"
env:
  node-ver: 16
jobs:
  build-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Generate codes in shared
        run: yarn codegen
      - name: Build shared package
        run: yarn build:shared
      - name: Upload generated GraphQL definitions
        uses: actions/upload-artifact@v3
        with:
          name: graphql-artifacts
          path: ./shared/src/apollo/generated
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: shared-artifacts
          path: ./shared/dist
  lint-and-test:
    runs-on: ubuntu-latest
    needs: build-shared
    strategy:
      matrix:
        workspace: [shared, backend, frontend]
    defaults:
      run:
        working-directory: "./${{ matrix.workspace }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - run: |
          mkdir -p ../shared/src/apollo/generated
          mkdir -p ../shared/dist
      - uses: actions/download-artifact@v3
        with:
          name: graphql-artifacts
          path: ../shared/src/apollo/generated
      - uses: actions/download-artifact@v3
        with:
          name: shared-artifacts
          path: ../shared/dist
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Run eslint-config-prettier
        run: yarn lint:conflict
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier
        run: yarn format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    needs: build-shared
    strategy:
      matrix:
        workspace: [backend, frontend]
    defaults:
      run:
        working-directory: "./${{ matrix.workspace }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - uses: actions/download-artifact@v3
        with:
          name: shared-artifacts
          path: ../shared/dist
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
