name: CI
on:
  push:
    paths-ignore:
      - CODEOWNERS
      - LICENSE
      - README.md
      - renovate.json
      - ".github/workflows/*.yml"
      - "!.github/workflows/ci.yml"
jobs:
  output-node-ver:
    runs-on: ubuntu-latest
    outputs:
      node-ver: ${{ steps.get-node-version.outputs.nodeVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Get node version from volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@eb5bfedc19c7a983377963749ff10f7e3f39fae4
  lint-and-test:
    runs-on: ubuntu-latest
    needs: output-node-ver
    strategy:
      matrix:
        workspace: [shared, backend, frontend]
    defaults:
      run:
        working-directory: "./${{ matrix.workspace }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{needs.output-node-ver.outputs.node-ver}}
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Run eslint-config-prettier
        run: yarn lint:conflict
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier
        run: yarn format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    needs: output-node-ver
    strategy:
      matrix:
        workspace: [shared, backend, frontend]
    defaults:
      run:
        working-directory: "./${{ matrix.workspace }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{needs.output-node-ver.outputs.node-ver}}
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Generate codes in shared
        working-directory: ./shared
        run: yarn codegen
      - name: Build shared package
        if: ${{ matrix.workspace }} != shared
        working-directory: ./shared
        run: yarn build
      - name: Build
        if: ${{ matrix.workspace }} == shared
        run: yarn build
