name: CI
on:
  push:
    paths-ignore:
      - CODEOWNERS
      - LICENSE
      - README.md
      - renovate.json
      - ".github/workflows/*.yml"
      - "!.github/workflows/ci.yml"
      - "!.github/workflows/prepare-ci.yml"
env:
  node-ver: 16
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["@gigantic-minecraft/seichi-keiba-shared", backend, frontend]
    steps:
      - name: Prepare for CI
        uses: GiganticMinecraft/seichi-keiba/.github/workflows/prepare-ci.yml@main
        with:
          node-ver: ${{ env.node-ver }}
      - name: Run eslint-config-prettier
        run: yarn workspace ${{ matrix.workspace }} lint:conflict
      - name: Run ESLint
        run: yarn workspace ${{ matrix.workspace }} lint
      - name: Run Prettier
        run: yarn workspace ${{ matrix.workspace }} format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [backend, frontend]
    steps:
      - name: Prepare for CI
        uses: GiganticMinecraft/seichi-keiba/.github/workflows/prepare-ci.yml@main
        with:
          node-ver: ${{ env.node-ver }}
      - name: Build
        run: yarn workspace ${{ matrix.workspace }} build
