name: CI
on:
  push:
    paths-ignore:
      - CODEOWNERS
      - LICENSE
      - README.md
      - renovate.json
      - .github/workflows/**
      - "!.github/workflows/ci.yml"
      - .github/actions/**
      - "!.github/actions/prepare-ci/action.yml"
env:
  node-ver: 16
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["@giganticminecraft/seichi-keiba-shared", backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for CI
        uses: ./.github/actions/prepare-ci
        with:
          node-ver: ${{ env.node-ver }}
      - name: Run eslint-config-prettier
        run: yarn workspace ${{ matrix.workspace }} lint:conflict
      - name: Run ESLint
        run: yarn workspace ${{ matrix.workspace }} lint
      - name: Run Prettier
        run: yarn workspace ${{ matrix.workspace }} format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for CI
        uses: ./.github/actions/prepare-ci
        with:
          node-ver: ${{ env.node-ver }}
      - name: Build
        run: yarn workspace ${{ matrix.workspace }} build
