name: CI
on:
  push:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install deps
        run: yarn install
      - name: Run eslint-config-prettier
        run: yarn lint:conflict
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier
        run: yarn format
      # TODO: Test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install deps
        run: yarn install
      # ref. https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
      - name: Load Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./yarn.lock') }}-${{ hashFiles('**.ts', '**.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('./yarn.lock') }}-
      - name: Build
        run: yarn build
