name: Prepare for CI
on:
  workflow_call:
    inputs:
      node-ver:
        type: number
        required: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      node-ver: ${{ inputs.node-ver }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-ver }}
          cache: yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Generate codes in shared
        run: yarn codegen
      - name: Build shared package
        run: yarn build:shared
